# Generated by Django 4.2 on 2023-05-13 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('edad', models.IntegerField()),
                ('fechaIngreso', models.DateField()),
                ('fechaAlta', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('numID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('O', 'Otro')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('numColegiado', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('especialidad', models.CharField(choices=[('Traumatología', 'Traumatología'), ('Cirugía', 'Cirugía'), ('Cardiología', 'Cardiología'), ('Neurología', 'Neurología'), ('Urología', 'Urología'), ('Oftalmología', 'Oftalmología')], max_length=30)),
                ('ingresos', models.ManyToManyField(to='gestHospital.ingreso')),
            ],
        ),
        migrations.AddField(
            model_name='ingreso',
            name='paciente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestHospital.paciente'),
        ),
    ]
